export {
  getACMGColor,
  getImpactColor,
  getTierColor,
  getScoreColor,
  getZygosityBadge,
  formatACMGDisplay,
  formatTierDisplay,
  formatConsequence,
  parseConsequences,
  getConsequenceColor,
  ConsequenceBadges,
  truncateSequence,
  formatAlleles,
} from './variant-helpers'
