import { Header, Footer } from '@/components'

export const metadata = {
  title: 'Terms of Service | Helena Bioinformatics',
  description: 'Terms and conditions for using the Helix Insight platform.',
}

export default function TermsOfServicePage() {
  return (
    <div className="h-full flex flex-col">
      <Header />
      <main className="flex-1 overflow-y-auto pt-8 pb-12 px-6">
        <article className="max-w-4xl mx-auto space-y-10">

          <div className="space-y-3">
            <h1 className="text-3xl font-semibold text-primary">Terms of Service</h1>
            <p className="text-sm text-muted-foreground">Last updated: February 2026</p>
            <p className="text-base text-foreground leading-relaxed">
              These Terms of Service (&quot;Terms&quot;) govern your access to and use of the Helix Insight platform operated by Helena Bioinformatics EOOD (&quot;Helena Bioinformatics&quot;, &quot;we&quot;, &quot;us&quot;). By accessing or using the platform, you agree to be bound by these Terms.
            </p>
          </div>

          <section className="space-y-4">
            <h2 className="text-lg font-semibold text-foreground">1. Service Description</h2>
            <div className="text-base text-muted-foreground leading-relaxed space-y-3">
              <p>Helix Insight is an AI-powered clinical decision support tool for genetic variant analysis. The platform provides automated variant annotation, ACMG classification, phenotype matching, literature analysis, and clinical interpretation to assist qualified geneticists and clinical laboratory professionals in their work.</p>
              <p><strong className="text-foreground">Helix Insight is not a medical device and is not intended to replace professional clinical judgment.</strong> All outputs are advisory in nature. The final interpretation and clinical decision for each variant remains the sole responsibility of the qualified geneticist or clinician using the platform.</p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-lg font-semibold text-foreground">2. Eligibility</h2>
            <div className="text-base text-muted-foreground leading-relaxed space-y-3">
              <p>The platform is intended for use by licensed clinical genetics laboratories, qualified geneticists, molecular biologists, and other healthcare professionals. By registering, you represent that you are authorized to upload and process genomic data on behalf of your organization and that your organization has obtained all necessary consents from data subjects.</p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-lg font-semibold text-foreground">3. Account Responsibilities</h2>
            <div className="text-base text-muted-foreground leading-relaxed space-y-3">
              <p>You are responsible for maintaining the confidentiality of your account credentials, all activities conducted under your account, ensuring that only authorized personnel access the platform, and notifying us immediately of any unauthorized use at security@helena.bio.</p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-lg font-semibold text-foreground">4. Data Ownership</h2>
            <div className="text-base text-muted-foreground leading-relaxed space-y-3">
              <p>You retain full ownership of all genomic data, phenotype information, and clinical data you upload to the platform. We do not claim any ownership rights over your data. We process your data solely to provide the analysis services you have requested, in accordance with our Data Processing Agreement.</p>
              <p>Analysis results generated by the platform (variant classifications, phenotype matches, literature references, clinical interpretations) are provided to you as part of the service and may be used by you without restriction in your clinical workflow.</p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-lg font-semibold text-foreground">5. Acceptable Use</h2>
            <div className="text-base text-muted-foreground leading-relaxed space-y-3">
              <p>You agree not to: upload data for which you do not have lawful processing authority; attempt to reverse-engineer, decompile, or extract source code from the platform; use the platform to identify individuals from anonymized or pseudonymized data; share your account credentials with unauthorized persons; use the platform for any purpose other than legitimate clinical genetics analysis; or attempt to circumvent security measures or access controls.</p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-lg font-semibold text-foreground">6. Clinical Decision Support Disclaimer</h2>
            <div className="text-base text-muted-foreground leading-relaxed space-y-3">
              <p>Helix Insight provides automated analysis to support clinical decision-making. The platform does not provide medical diagnoses, does not replace the expertise of qualified geneticists, and does not constitute medical advice. Variant classifications and clinical interpretations generated by the platform should be reviewed, validated, and confirmed by qualified professionals before being used in clinical reports or patient care decisions.</p>
              <p>While we strive for accuracy and follow established standards (ACMG/AMP guidelines, ClinVar, gnomAD), automated analysis may contain errors. We strongly recommend that all clinically significant findings be independently verified.</p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-lg font-semibold text-foreground">7. Service Availability</h2>
            <div className="text-base text-muted-foreground leading-relaxed space-y-3">
              <p>We aim to maintain high availability but do not guarantee uninterrupted service. Planned maintenance will be communicated in advance. We are not liable for service interruptions caused by factors beyond our reasonable control.</p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-lg font-semibold text-foreground">8. Limitation of Liability</h2>
            <div className="text-base text-muted-foreground leading-relaxed space-y-3">
              <p>To the maximum extent permitted by applicable law, Helena Bioinformatics shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from or related to your use of the platform, including but not limited to clinical decisions made based on platform outputs.</p>
              <p>Our total liability for any claims arising under these Terms shall not exceed the total fees paid by you in the 12 months preceding the claim.</p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-lg font-semibold text-foreground">9. Intellectual Property</h2>
            <div className="text-base text-muted-foreground leading-relaxed space-y-3">
              <p>The Helix Insight platform, including its software, algorithms, user interface, documentation, and branding, is the intellectual property of Helena Bioinformatics. These Terms do not grant you any rights to our intellectual property beyond the limited right to use the platform as intended.</p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-lg font-semibold text-foreground">10. Termination</h2>
            <div className="text-base text-muted-foreground leading-relaxed space-y-3">
              <p>Either party may terminate these Terms with 30 days written notice. We may suspend or terminate your access immediately if you violate these Terms or engage in activities that compromise platform security. Upon termination, we will delete your genomic data in accordance with our data retention policy and the applicable DPA.</p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-lg font-semibold text-foreground">11. Governing Law</h2>
            <div className="text-base text-muted-foreground leading-relaxed space-y-3">
              <p>These Terms are governed by the laws of the Republic of Bulgaria and the European Union. Any disputes shall be resolved by the competent courts in Sofia, Bulgaria, without prejudice to any mandatory consumer protection provisions under applicable law.</p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-lg font-semibold text-foreground">12. Contact</h2>
            <div className="text-base text-muted-foreground leading-relaxed space-y-3">
              <p>For questions about these Terms, contact us at legal@helena.bio.</p>
            </div>
          </section>

        </article>
      <Footer />
      </main>
    </div>
  )
}
